base_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')), # <--
    path('', include('treasurehunt.urls')),
    path('',include('pwa.urls')),
]

treasurehunt/urls.py
from django.urls import path
from . import views
from django.views.static import serve
from django.conf.urls.static import static
from django.conf import settings
app_name = 'treasurehunt'

urlpatterns = [
    path('', views.index, name='index'),
    path('question/', views.question, name="question"),
    path('logout/', views.user_logout, name="logout"),
    # path('register/', views.register, name='register'),
   # path('login/', views.user_login, name='login'),


    path('leaderboard/', views.leaderboard, name='leaderboard')
] 
urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

treasurehunt/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime
from datetime import datetime
# Create your models here.
class Score(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    score = models.PositiveIntegerField(default=0)
    ban=models.BooleanField(default=False)
    timestamp = models.DateTimeField(default=datetime.now)

    def __str__(self):
        return self.user.username

class level(models.Model):
    l_number = models.IntegerField()
    numuser = models.IntegerField(default=0)
    accuracy = models.FloatField(default=0)
    wrong = models.IntegerField(default=0)


    def __unicode__(self):
        return self.text


class Answer(models.Model):
    answer = models.CharField(max_length=255)


class AnswerChecker(models.Model):
    index = models.PositiveIntegerField(default=0, unique=True)
    answer = models.CharField(max_length=255)

    def __str__(self):
        return self.answer

    def ans_value(self):
        return self.answer

treasurehunt/forms.py
from django import forms
from django.contrib.auth.models import User
from . import models


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={'placeholder': 'Enter the Password'}))
    confirm_password = forms.CharField(widget=forms.PasswordInput(
        attrs={'placeholder': 'Reenter the password'}))

    class Meta():
        model = User
        fields = ('username', 'email', 'password', 'confirm_password')


class Answer(forms.ModelForm):
    answer = forms.CharField()

    class Meta():
        model = models.Answer
        fields = ('answer', )

treasurehunt/views.py
from django.shortcuts import render
from . import forms
# Create your views here.
from treasurehunt import models
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib import messages
import datetime
import time
from termcolor import colored

def index(request):
    return render(request, 'treasurehunt/index.html')


def register(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('treasurehunt:question'))
    registered = False

    if request.method == 'POST':
        user_form = forms.UserForm(data=request.POST)
        if user_form.is_valid():
            passmain = user_form.cleaned_data['password']
            passverify = user_form.cleaned_data['confirm_password']
            if passmain == passverify:
                user = user_form.save()
                user.set_password(user.password)
                user.save()

                score = models.Score()
                score.user = user
                score.save()

                registered = True
            else:
                return HttpResponse("Password Don't Match")
        else:
            print(user_form.errors)
    else:
        user_form = forms.UserForm()

    return render(request, 'treasurehunt/signup.html', {
        'user_form': user_form,
        'registered': registered
    })


def user_login(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('treasurehunt:question'))
    registered = False

    if request.method == 'POST':
        user_form = forms.UserForm(data=request.POST)
        if user_form.is_valid():
            passmain = user_form.cleaned_data['password']
            passverify = user_form.cleaned_data['confirm_password']
            if passmain == passverify:
                user = user_form.save()
                user.set_password(user.password)
                user.save()

                score = models.Score()
                score.user = user
                score.save()

                registered = True
            else:
                return HttpResponse("Password Don't Match")
        else:
            print(user_form.errors)
    else:
        user_form = forms.UserForm()

    return render(request, 'treasurehunt/signup.html', {
        'user_form': user_form,
        'registered': registered
    })


# def user_login(request):
#     if request.user.is_authenticated:
#         return HttpResponseRedirect(reverse('treasurehunt:question'))
#     if request.method == 'POST':
#         username = request.POST.get('username')
#         password = request.POST.get('password')

#         user = authenticate(username=username, password=password)

#         if user:
#             if user.is_active:
#                 login(request, user)
#                 return HttpResponseRedirect(reverse('treasurehunt:question'))
#             else:
#                 return HttpResponse("ACCOUNT NOT ACTIVE")
#         else:
#             print("Someone tried to login and failed")
#             print("UserName : {} and password {} ".format(username, password))
#             messages.error(request, "Invalid Login Details!")
#             return render(request, 'treasurehunt/login.html')
#     else:
#         return render(request, 'treasurehunt/login.html')

def invalid_login(request):
    return render(request,'treasurehunt/invalidlogin.html')


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('treasurehunt:index'))


@login_required
def question(request):

    question_fixed = [
        '0', '1', '2', '3', '4', '5', '6',
        '7', '8', '9', '10',
        '11', '12', '13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29'  ]

    current_user = request.user
    try:
        sc = models.Score.objects.get(user__exact=current_user)
    except:
        score = models.Score()
        score.user = current_user
        score.save()
        sc = models.Score.objects.get(user__exact=current_user)

    ans_fixed = models.AnswerChecker.objects.get(index__exact=sc.score)
    level = models.level.objects.get(l_number=sc.score+1)
    if sc.ban==True:
        return render(request, 'treasurehunt/banned.html',{'score':sc.score})
    else:

        if sc.score == 20:
            return render(request, 'treasurehunt/hunt_win.html',{'score':sc.score})
        else:
            if request.method == 'POST':
                question_form = forms.Answer(data=request.POST)
                if question_form.is_valid():
                    ans = question_form.cleaned_data['answer']
                    

                    if ans.lower() == ans_fixed.ans_value():
                        sc.score = sc.score + 1
                        sc.timestamp = datetime.datetime.now()
                        sc.save()
                        level.numuser = level.numuser + 1
                        level.accuracy = round(level.numuser/(float(level.numuser + level.wrong)),2)
                        level.save()
                        anslog='Level: '+str(sc.score+1) +' user: '+str(current_user)+' answer: '+str(ans)
                        print(colored(anslog,'green'))
                        return render(request, 'treasurehunt/level_transition.html',{'score':sc.score})

                    else:
                        level.wrong=level.wrong+1
                        level.save()
                        anslog='Level: '+str(sc.score+1) +' user: '+str(current_user)+' answer: '+str(ans)
                        print(colored(anslog,'red'))
                        return render(request, 'treasurehunt/level_fail.html',{'score':sc.score})
                else:
                    
                    return render(
                        request, 'treasurehunt/question.html', {
                            'question_form': question_form,
                            'score': sc.score,
                            'question_fixed': question_fixed[sc.score],
                            'level':level
                        })
            else:
                question_form = forms.Answer()
            
            return render(
                request, 'treasurehunt/question.html', {
                    'question_form': question_form,
                    'score': sc.score,
                    'question_fixed': question_fixed[sc.score],
                    'level':level
                })


def leaderboard(request):
    leader = models.Score.objects.all().filter(ban=False).order_by('-score','timestamp')
    
    if len(leader) >= 10:
        user_name = []
        for x in leader:
            user_name.append((x.user.username, x.score,x.timestamp))
        return render(request, 'treasurehunt/leaderboard.html', {
            'user_name': user_name,
        })
    else:
        user_name = []
        for x in leader:
            user_name.append((x.user.username, x.score,x.timestamp))
        return render(request, 'treasurehunt/leaderboard.html', {
            'user_name': user_name,
        })


#t = Score.objects.all().order_by('-score')
# t[0].user.username

treasurehunt/templates/treasurehunt/banned.html
{% extends "treasurehunt/base.html" %}
{% load static %}
{% block content %}



<!-- Product Section Begin -->
<section class="product-page spad">
	<div class="container">
	
		<div class="row">
			<div class="col-lg-12">
				<div class="product__page__content ">
					<div class="product__page__title">
						<div class="row ">
							<div class="col-lg-8 col-md-8 col-sm-6">
								<div class="section-title">
									<h1 class="hero-text">Banned 😞</h1>
									<p class="text-muted">Sorry You have been banned temporarily! Please try after 30 min.</p>
								</div>
							</div>
							<div class="col-lg-4 col-md-4 col-sm-6">

							</div>
						</div>
					</div>
					<div class="row">
						<div class="blog__details__form" style="width:100%; 
						/* margin-bottom:50px; */
						">
							<!-- <a href="{% url 'treasurehunt:question' %}" >
								<button type="button" class="site-btn">
									Try Again
								</button>
							</a> -->
							
						</div>
						<div class="blog__details__text">
							
                        </div>
						<div class="blog__details__item__text" style="width:100%">
							<!-- <div style="width:100%;height:0;padding-bottom:42%;position:relative;"><iframe src="https://giphy.com/embed/fe4dDMD2cAU5RfEaCU" width="100%" height="100%" style="position:absolute" frameBorder="0" class="giphy-embed" allowFullScreen></iframe></div><p><a href="https://giphy.com/gifs/ban-banned-admin-fe4dDMD2cAU5RfEaCU">via GIPHY</a></p> -->
							<img src="{% static 'img/ban.gif' %}" alt="" style="width:100%">
							
						</div>
					
						<div class="blog__details__form mt-3" style="width:100%">
							<a href="{% url 'treasurehunt:logout' %}" >
								<button class="c-button c-button--primary">Logout</button>
							</a>
							
						</div>
					</div>
				</div>

			</div>
		</div>
	</div>
	</div>
</section>
<!-- Product Section End -->

{% endblock content %}

treasurehunt/templates/treasurehunt/base.html
<!DOCTYPE html>
{% load pwa %}
{% load static%}
{% load socialaccount %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
        integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'styles/style.css' %}" type="text/css">
</head>

<body>
    <div class="l-wrapper">
    <nav class="navbar navbar-expand-lg navbar-dark navbar-bg-dark">
        <div class="container-fluid">
            <a href="{% url 'treasurehunt:index' %}">
                <img class="c-logo logo-style" src="https://hack4tkm.in/images/hack4tkmlogo.png" alt="">
                <!-- <img src="{% static 'img/logo.png' %}" alt=""> -->
               
            </a>
            <!-- <a class="navbar-brand" href="#"> <img class="c-logo"
                    src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/813538/km-logo-color.svg" draggable="false" /></a> -->
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page"
                            href="{% url 'treasurehunt:question' %}">Questions</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page"
                            href="{% url 'treasurehunt:leaderboard' %}">Leaderboard</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% static 'files/Rules.pdf'%}">Rules</a>
                    </li>

                </ul>
              
                {% if user.is_authenticated %}
                <span class="nav-link active" aria-current="page" href="#">
                    🤖 {{user.username}} | 🏆 Score : {{score}}
                    <a href="{% url 'treasurehunt:logout' %}" target="_blank">
                        <button class="c-button c-button--primary">Logout</button>
                    </a>
                </span>
                {% else %}
                <a href="{% provider_login_url 'google' %}" target="_blank">
                    <button class="c-button c-button--primary">Login</button>
                </a>
               
                {% endif %}
            </div>
        </div>
    </nav>
    <div class="c-header">
    </div>
    {% block content%} {% endblock content%}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
    <script src="{% static 'js/script.js' %}"></script>
</body>

</html>

treasurehunt/templates/treasurehunt/error.html
{% extends "treasurehunt/base.html" %}
{% load static %}
{% block content %}



<!-- Product Section Begin -->

<section class="product-page spad">
	<div class="container">
	
		<div class="row">
			<div class="col-lg-12">
				<div class="product__page__content ">
					<div class="product__page__title">
						<div class="row ">
							<div class="col-lg-8 col-md-8 col-sm-6">
								<div class="section-title">
									<h1 class="hero-text">Some error occured 🥲</h1>
									<p class="text-muted">Sorry,Please try again</p>
								</div>
							</div>
							<div class="col-lg-4 col-md-4 col-sm-6">

							</div>
						</div>
					</div>
					<div class="row">
						<div class="blog__details__form" style="width:100%; 
						/* margin-bottom:50px; */
						">
							<!-- <a href="{% url 'treasurehunt:question' %}" >
								<button type="button" class="site-btn">
									Try Again
								</button>
							</a> -->
							
						</div>
						<div class="blog__details__text">
							
                        </div>
						<div class="blog__details__form mt-3 mb-3" style="width:100%">
							<a href="{% url 'treasurehunt:question' %}" >
								<button class="c-button c-button--primary">Try Again</button>
							</a>
							
						</div>
						<div class="blog__details__item__text" style="width:100%">
							<!-- <div style="width:100%;height:0;padding-bottom:42%;position:relative;"><iframe src="https://giphy.com/embed/fe4dDMD2cAU5RfEaCU" width="100%" height="100%" style="position:absolute" frameBorder="0" class="giphy-embed" allowFullScreen></iframe></div><p><a href="https://giphy.com/gifs/ban-banned-admin-fe4dDMD2cAU5RfEaCU">via GIPHY</a></p> -->
							<img src="{% static 'img/error.gif' %}" alt="" style="width:100%">
							
						</div>
					
						
					</div>
				</div>

			</div>
		</div>
	</div>
	</div>
</section>
<!-- Product Section End -->

{% endblock content %}

treasurehunt/templates/treasurehunt/hunt_win.html
{% extends "treasurehunt/base.html" %}
{% load static %}
{% block content %}



<!-- Product Section Begin -->

<section class="product-page spad">
	<div class="container">
	
		<div class="row">
			<div class="col-lg-12">
				<div class="product__page__content ">
					<div class="product__page__title">
						<div class="row ">
							<div class="col-lg-8 col-md-8 col-sm-6">
								<div class="section-title">
									<h1 class="hero-text">Hunt Compleated 🎉</h1>
									<p class="text-muted">You are awsome!!!!</p>
								</div>
							</div>
							<div class="col-lg-4 col-md-4 col-sm-6">

							</div>
						</div>
					</div>
					<div class="row">
						<div class="blog__details__form" style="width:100%; 
						/* margin-bottom:50px; */
						">
							<!-- <a href="{% url 'treasurehunt:question' %}" >
								<button type="button" class="site-btn">
									Try Again
								</button>
							</a> -->
							
						</div>
						<div class="blog__details__text">
							
                        </div>
						<div class="blog__details__form mt-3 mb-3" style="width:100%">
							<a href="{% url 'treasurehunt:leaderboard' %}" >
								<button class="c-button c-button--primary">Leaderboard</button>
							</a>
							
						</div>
						<div class="blog__details__item__text" style="width:100%">
							<!-- <div style="width:100%;height:0;padding-bottom:42%;position:relative;"><iframe src="https://giphy.com/embed/fe4dDMD2cAU5RfEaCU" width="100%" height="100%" style="position:absolute" frameBorder="0" class="giphy-embed" allowFullScreen></iframe></div><p><a href="https://giphy.com/gifs/ban-banned-admin-fe4dDMD2cAU5RfEaCU">via GIPHY</a></p> -->
							<img src="{% static 'img/winner.gif' %}" alt="" style="width:100%">
							
						</div>
					
						
					</div>
				</div>

			</div>
		</div>
	</div>
	</div>
</section>
<!-- Product Section End -->

{% endblock content %}

treasurehunt/templates/treasurehunt/index.html
{% extends "treasurehunt/base.html" %}

{% block content %}
{% load static %}
<div class="container">
    <div class="row">
        <div class="col-md-4 col-md-push-8">
            <div class="hero-graphics-wraper">
                <div class="container">
                    <div class="loader"><i></i>
                        <div class="shadow"></div>
                    </div>
                    <div class="icons"><i class="fas fa-rocket"></i>
                        <div class="clouds"><i class="fas fa-cloud" style="--i: 1"></i><i class="fas fa-cloud"
                                style="--i: 2"></i><i class="fas fa-cloud" style="--i: 3"></i><i
                                class="fas fa-cloud" style="--i: 4"></i></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-8 col-md-pull-4">
            <div class="hero-wraper">
                <h1 class="hero-text">Welcome to the center of Universe</h1>
                <h3>Catch up with the people and tech defining the industry. Build skills, explore new tools,
                    and celebrate the developer community.</h3>
            </div>
            <div class="mt-5">
                <a href="{% url 'treasurehunt:question' %}"> <button class="c-button c-button--primary">Questions</button> <i class="fa fa-angle-right"></i></a>
               
            </div>
        </div>
    </div>
</div>
   
                         
                        

{% endblock content %}

treasurehunt/templates/treasurehunt/leaderboard.html
{% extends "treasurehunt/base.html" %}
{% load static %}
{% block content %}

<div class="l-grid__item l-grid__item--sticky">
	<div class="c-card u-bg--light-gradient u-text--dark">
	  <div class="c-card__body">
		<div class="u-display--flex u-justify--space-between">
		  <div class="u-text--left">
			<div class="u-text--small">My Rank</div>
			<h2>3rd Place</h2>
		  </div>
		  <div class="u-text--right">
			<div class="u-text--small">My Score</div>
			<h2>24</h2>
		  </div>
		</div>
	  </div>
	</div>
	<!-- <div class="c-card">
	  <div class="c-card__body">
		<div class="u-text--center" id="winner"></div>
	  </div>
	</div> -->
  </div>
  <div class="l-grid__item">
	<div class="c-card">
	  <div class="c-card__header">
		<h3>Leaderboard</h3>
		<select class="c-select">
		  <option selected="selected">Sunday, Feb. 23 - Sunday, Feb. 30</option>
		</select>
	  </div>
	  <div class="c-card__body">
		<ul class="c-list" id="list">
		  <li class="c-list__item">
			<div class="c-list__grid">
			  <div class="u-text--left u-text--small u-text--medium">Rank</div>
			  <div class="u-text--left u-text--small u-text--medium">Name</div>
			  <div class="u-text--right u-text--small u-text--medium"># Points</div>
			</div>
		  </li>
		  {% for x,y,z in user_name  %}
		  <li class="c-list__item">
			<div class="c-list__grid">
				<div class="c-flag c-place u-bg--transparent">1</div>
				<div class="c-media">
					<div class="c-media__content">
						<div class="c-media__title">{{x}}</div>
						<a class="c-media__link u-text--small" href="#">{{z}}</a>
						
					</div>
				</div>
				<div class="u-text--right c-kudos">
					<div class="u-mt--8">
						<strong>{{y}}</strong>
						<span id='random-imoji'></span>
					</div>
				</div>
			</div>
		</li>
		{% endfor %}
		</ul>
	  </div>
	</div>
  </div>
                                 
{% endblock content %}
















   

treasurehunt/templates/treasurehunt/level_fail.html
{% extends "treasurehunt/base.html" %}
{% load static %}
{% block content %}



<!-- Product Section Begin -->

<section class="product-page spad">
	<div class="container">
	
		<div class="row">
			<div class="col-lg-12">
				<div class="product__page__content ">
					<div class="product__page__title">
						<div class="row ">
							<div class="col-lg-8 col-md-8 col-sm-6">
								<div class="section-title">
									<h1 class="hero-text">Wrong Answer 🥲</h1>
									<p class="text-muted">Sorry,Please try again</p>
								</div>
							</div>
							<div class="col-lg-4 col-md-4 col-sm-6">

							</div>
						</div>
					</div>
					<div class="row">
						<div class="blog__details__form" style="width:100%; 
						/* margin-bottom:50px; */
						">
							<!-- <a href="{% url 'treasurehunt:question' %}" >
								<button type="button" class="site-btn">
									Try Again
								</button>
							</a> -->
							
						</div>
						<div class="blog__details__text">
							
                        </div>
						<div class="blog__details__form mt-3 mb-3" style="width:100%">
							<a href="{% url 'treasurehunt:question' %}" >
								<button class="c-button c-button--primary">Try Again</button>
							</a>
							
						</div>
						<div class="blog__details__item__text" style="width:100%">
							<!-- <div style="width:100%;height:0;padding-bottom:42%;position:relative;"><iframe src="https://giphy.com/embed/fe4dDMD2cAU5RfEaCU" width="100%" height="100%" style="position:absolute" frameBorder="0" class="giphy-embed" allowFullScreen></iframe></div><p><a href="https://giphy.com/gifs/ban-banned-admin-fe4dDMD2cAU5RfEaCU">via GIPHY</a></p> -->
							<img src="{% static 'img/wrong.gif' %}" alt="" style="width:100%">
							
						</div>
					
						
					</div>
				</div>

			</div>
		</div>
	</div>
	</div>
</section>
<!-- Product Section End -->

{% endblock content %}

treasurehunt/templates/treasurehunt/level_transition.html
{% extends "treasurehunt/base.html" %}
{% load static %}
{% block content %}



<!-- Product Section Begin -->
<section class="product-page spad">
	<div class="container">
	
		<div class="row">
			<div class="col-lg-12">
				<div class="product__page__content ">
					<div class="product__page__title">
						<div class="row ">
							<div class="col-lg-8 col-md-8 col-sm-6">
								<div class="section-title">
									<h1 class="hero-text">Correct Answer 🎉</h1>
									<p class="text-muted">You are awsome!!!!</p>
								</div>
							</div>
							<div class="col-lg-4 col-md-4 col-sm-6">

							</div>
						</div>
					</div>
					<div class="row">
						<div class="blog__details__form" style="width:100%; 
						/* margin-bottom:50px; */
						">
							<!-- <a href="{% url 'treasurehunt:question' %}" >
								<button type="button" class="site-btn">
									Try Again
								</button>
							</a> -->
							
						</div>
						<div class="blog__details__text">
							
                        </div>
						<div class="blog__details__form mt-3 mb-3" style="width:100%">
							<a href="{% url 'treasurehunt:question' %}" >
								<button class="c-button c-button--primary">Next Question</button>
							</a>
							
						</div>
						<div class="blog__details__item__text" style="width:100%">
							<!-- <div style="width:100%;height:0;padding-bottom:42%;position:relative;"><iframe src="https://giphy.com/embed/fe4dDMD2cAU5RfEaCU" width="100%" height="100%" style="position:absolute" frameBorder="0" class="giphy-embed" allowFullScreen></iframe></div><p><a href="https://giphy.com/gifs/ban-banned-admin-fe4dDMD2cAU5RfEaCU">via GIPHY</a></p> -->
							<img src="{% static 'img/clap.gif' %}" alt="" style="width:100%">
							
						</div>
					
						
					</div>
				</div>

			</div>
		</div>
	</div>
	</div>
</section>
<!-- Product Section End -->

{% endblock content %}

treasurehunt/templates/treasurehunt/login.html
{% extends "treasurehunt/base.html" %}
{% block content %}
{% load static %}
<br><br><br><br><br>
<!-- Login Container -->
{% for message in messages %}

<div class="alert alert-success">
    <a class="close" href="#" data-dismiss="alert">×</a>

    {{ message }}

</div>
{% endfor %}
<div class="login">
  <form class="contact-from" action="{% url 'treasurehunt:login' %}" method="post">
    <div class="container">
      {% csrf_token %}
      <br>
      <h1>Login</h1>
      <br>
      <p>Login to your account using your credentials.</p>
      <hr>
      <div class="col-md-6">
      <input class="text" type="text" name="username" placeholder="Username" required="">
      </div>
      <div class="col-md-6">
      <input class="text" type="password" name="password" placeholder="Password" required="">
      </div>
      <br>
      <br>
      <div class="col-md-3">
      <input class="btn btn-outline-primary" type="submit" value="Login">
      </div>
      <br>
      <br>
      <hr>
      <p>Not a member ? <a href="{% url 'treasurehunt:register' %}">Sign Up </a></p>

    </div>
  </form>
</div>
<!-- Login Container End -->
{% endblock content %}

treasurehunt/templates/treasurehunt/question.html
{% extends "treasurehunt/base.html" %}
{% load static %}
{% block content %}



<!-- Product Section Begin -->
<section class="product-page spad">
	<div class="container">
	
		<div class="row">
			<div class="col-lg-12">
				<div class="product__page__content ">
					<div class="product__page__title">
						<div class="row ">
							<div class="col-lg-8 col-md-8 col-sm-6">
								<div class="section-title">
									<h1 class="hero-text">Level : {{level.l_number}} </h1>
									<p class="text-muted">Users cleared:{{level.numuser}} Accuracy:{{level.accuracy}}</p>
								</div>
							</div>
							<div class="col-lg-4 col-md-4 col-sm-6">

							</div>
						</div>
					</div>
					<div class="row">
						<div class="blog__details__form" style="width:100%; 
						/* margin-bottom:50px; */
						">
							<!-- <a href="{% url 'treasurehunt:question' %}" >
								<button type="button" class="site-btn">
									Try Again
								</button>
							</a> -->
							
						</div>
						<div class="blog__details__text">
							
                        </div>
						<div class="blog__details__item__text" style="width:100%">
							<!-- <div style="width:100%;height:0;padding-bottom:42%;position:relative;"><iframe src="https://giphy.com/embed/fe4dDMD2cAU5RfEaCU" width="100%" height="100%" style="position:absolute" frameBorder="0" class="giphy-embed" allowFullScreen></iframe></div><p><a href="https://giphy.com/gifs/ban-banned-admin-fe4dDMD2cAU5RfEaCU">via GIPHY</a></p> -->
							<img src="{% static 'images/'%}{{question_fixed}}.png" alt="" style="width:100%">
							
						</div>
					
						<div class="blog__details__form mt-3" style="width:100%">
							<form method="POST" enctype="multipart/form-data">
								<div class="row">
									<div class="col-lg-6 col-md-6 col-sm-6">
										{% csrf_token %}
										{{question_form.as_p}}
									</div>

									<div class="col-lg-12">

										<button type="submit"  class="c-button c-button--primary">Check</button>
									</div>
								</div>
							</form>
					
							
						</div>
					</div>
				</div>

			</div>
		</div>
	</div>
	</div>
</section>

{% endblock content %}